import Link from 'next/link';
import { prisma } from '@/lib/db';
import { centsToRateDisplay } from '@/lib/money';
import { demoOverview } from '@/server/services/demo';
import { Alert, Badge, Card, StatTile } from '@/components/ui';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'ExpertOps — synthetic demo',
  description: 'A read-only view of ExpertOps running on synthetic data.',
};

/**
 * The anonymous demo.
 *
 * Read-only, and only ever renders what `demo.ts` hands it. There is no
 * session here, no capability check to widen by accident, and no form: a
 * visitor can look and nothing else.
 */
export default async function DemoPage() {
  const overview = await demoOverview(prisma);

  return (
    <div className="mx-auto max-w-5xl space-y-5 px-4 py-8 sm:px-6">
      <header>
        <h1 className="page-title">ExpertOps — synthetic demo</h1>
        <p className="page-subtitle">
          A read-only look at an expert-network operations tool, running on a network of people who
          do not exist.
        </p>
      </header>

      <Alert tone="warning">
        <strong>Everything here is synthetic.</strong> The {overview.network.totalExperts} experts,
        the projects and the seats were generated by a seeding script. Nobody was contacted, email
        is written to an in-app outbox and never sent, and no payment has ever been executed — there
        is no state in the schema that means &ldquo;paid&rdquo;. This is an independent project and
        is not affiliated with any company.
      </Alert>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <StatTile label="Experts in the network" value={overview.network.totalExperts} />
        <StatTile
          label="Seats confirmed"
          value={overview.projects.reduce((total, project) => total + project.seatsFilled, 0)}
        />
        <StatTile label="Open opportunities" value={overview.openOpportunities} />
        <StatTile
          label="Background jobs run"
          value={overview.jobsSucceeded}
          tone={overview.jobsFailed > 0 ? 'warning' : 'success'}
        />
      </div>

      <Card
        title="What this tool is for"
        description="Sourcing, screening, staffing and delivery for a network of external experts."
      >
        <ol className="list-decimal space-y-1.5 pl-5 text-sm text-ink-700">
          <li>
            Somebody applies to a published opportunity, or an operator enters them. Either way a
            human reads the application.
          </li>
          <li>
            They are screened against an immutable rubric version. A reviewer scores it and either
            asks for a revision or recommends approval.
          </li>
          <li>
            <strong>A person qualifies them.</strong> Nothing is scored automatically and no
            protected attribute is anywhere near the decision.
          </li>
          <li>
            Matching ranks qualified experts against a project&rsquo;s requirements and explains
            every exclusion. It never contacts anyone.
          </li>
          <li>
            Outreach needs an approval from a second account before a single message is queued.
          </li>
          <li>
            Onboarding, verification and seat confirmation are each an explicit human action. Work
            is assigned, submitted, reviewed, and prepared for payment somewhere else.
          </li>
        </ol>
      </Card>

      <Card title="The network" description="Aggregate only. No individual record is shown here.">
        <div className="flex flex-wrap gap-2">
          {overview.network.expertsByStatus.map((row) => (
            <span
              key={row.status}
              className="rounded-lg border border-ink-200 px-3 py-1.5 text-sm text-ink-800"
            >
              {row.status.replace(/_/g, ' ').toLowerCase()}{' '}
              <strong className="tabular-nums">{row.count}</strong>
            </span>
          ))}
        </div>
      </Card>

      <Card
        title="Projects"
        description="Seats are consumed by an explicit confirmation, one at a time."
      >
        <div className="scroll-x">
          <table className="data">
            <thead>
              <tr>
                <th>Code</th>
                <th>Project</th>
                <th>Status</th>
                <th>Seats</th>
                <th>Required skill</th>
                <th>Rate ceiling</th>
              </tr>
            </thead>
            <tbody>
              {overview.projects.map((project) => (
                <tr key={project.code}>
                  <td className="font-mono text-xs">{project.code}</td>
                  <td>{project.title}</td>
                  <td>
                    <Badge tone={project.status === 'ACTIVE' ? 'success' : 'muted'}>
                      {project.status.toLowerCase()}
                    </Badge>
                  </td>
                  <td className="tabular-nums">
                    {project.seatsFilled}/{project.seatsRequested}
                  </td>
                  <td className="text-xs">{project.requirements.join(', ') || '—'}</td>
                  <td className="text-xs tabular-nums">
                    {project.maxHourlyRateCents
                      ? centsToRateDisplay(project.maxHourlyRateCents, 'USD')
                      : '—'}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      {overview.ranking && (
        <Card
          title={`Matching, worked through on ${overview.ranking.projectCode}`}
          description={`${overview.ranking.algorithmVersion} · ${overview.ranking.consideredCount} considered · ${overview.ranking.rankedCount} ranked · ${overview.ranking.excludedCount} excluded`}
        >
          <p className="text-sm text-ink-700">
            Deterministic rules, no language model. The same inputs always produce the same ranking,
            and every exclusion says why — which is the part an operator has to be able to defend.
          </p>

          <div className="mt-3 grid gap-4 lg:grid-cols-2">
            <div>
              <h3 className="section-title">Top of the ranking</h3>
              <p className="field-hint">
                Identified by reference only. Names and contact details are not part of this view.
              </p>
              <ul className="mt-2 space-y-1">
                {overview.ranking.top.map((row) => (
                  <li
                    key={row.reference}
                    className="flex items-center justify-between rounded-lg border border-ink-200 px-3 py-1.5 text-sm"
                  >
                    <span className="font-mono text-xs">{row.reference}</span>
                    <span className="tabular-nums text-ink-700">
                      #{row.rank} · score {row.score}
                    </span>
                  </li>
                ))}
              </ul>
            </div>

            <div>
              <h3 className="section-title">Why people were excluded</h3>
              <p className="field-hint">A hard filter, applied before scoring.</p>
              <ul className="mt-2 space-y-1">
                {overview.ranking.exclusions.map((row) => (
                  <li
                    key={row.reason}
                    className="rounded-lg border border-ink-200 px-3 py-1.5 text-sm text-ink-700"
                  >
                    <strong className="tabular-nums">{row.count}</strong> — {row.reason}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </Card>
      )}

      <Card
        title="What this view deliberately does not show"
        description="The demo is a separate projection, not an account with the permissions turned down."
      >
        <ul className="list-disc space-y-1 pl-5 text-sm text-ink-700">
          <li>Candidates, applications and screening answers — those are people&rsquo;s words.</li>
          <li>
            The simulated outbox, which holds single-use sign-in links. A link read from it would be
            a working session.
          </li>
          <li>Payment items and batches, the activity history, and operator identities.</li>
          <li>Internal notes on any record, and anything belonging to a non-synthetic record.</li>
        </ul>
        <p className="mt-3 text-sm text-ink-600">
          Signing in as an operator shows all of it. That needs an account, and there is no shared
          demo password.
        </p>
      </Card>

      <Card title="See the applicant side">
        <p className="text-sm text-ink-700">
          The opportunities below are practice listings — they are not real jobs and no work or
          compensation follows from applying.
        </p>
        <div className="mt-3 flex flex-wrap gap-2">
          <Link className="btn btn-primary" href="/apply/opportunities">
            Open opportunities
          </Link>
          <Link className="btn btn-secondary" href="/login">
            Operator sign-in
          </Link>
        </div>
      </Card>

      <footer className="pb-4 text-xs text-ink-500">
        Read-only. Nothing on this page can be changed from here, and no form on it submits
        anything.
      </footer>
    </div>
  );
}
