import Link from 'next/link';
import { prisma } from '@/lib/db';
import { centsToRateDisplay } from '@/lib/money';
import { demoOverview } from '@/server/services/demo';
import { Alert, Badge, Card, StatTile, StatusBadge, TableShell } from '@/components/ui';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'ExpertOps — read-only demo',
  description: 'A read-only view of ExpertOps running on sample data.',
};

const STEPS = [
  {
    title: 'Applications arrive',
    body: 'Somebody applies to a published opportunity, or an operator enters them. Either way a person reads the application.',
  },
  {
    title: 'Screening against a fixed rubric',
    body: 'A reviewer scores the submission against an immutable rubric version and either asks for a revision or recommends approval.',
  },
  {
    title: 'A person qualifies them',
    body: 'Nothing is scored automatically, and no protected attribute is anywhere near the decision.',
  },
  {
    title: 'Matching explains itself',
    body: 'Qualified experts are ranked against a project’s requirements, and every exclusion says why. Matching never contacts anyone.',
  },
  {
    title: 'Outreach needs a second approval',
    body: 'A different operator approves a batch before a single message is queued.',
  },
  {
    title: 'Onboarding, seats and delivery',
    body: 'Verification and seat confirmation are each an explicit human action. Work is submitted, reviewed and prepared for payment somewhere else.',
  },
];

/**
 * The anonymous demo.
 *
 * Read-only, and only ever renders what `demo.ts` hands it. There is no
 * session here, no capability check to widen by accident, and no form: a
 * visitor can look and nothing else.
 */
export default async function DemoPage() {
  const overview = await demoOverview(prisma);
  const seatsFilled = overview.projects.reduce((total, project) => total + project.seatsFilled, 0);
  const seatsRequested = overview.projects.reduce(
    (total, project) => total + project.seatsRequested,
    0,
  );

  return (
    <div className="space-y-6">
      <header className="flex flex-wrap items-end justify-between gap-4">
        <div className="min-w-0">
          <span className="eyebrow">Read-only demo</span>
          <h1 className="page-title">Inside the ExpertOps demo workspace</h1>
          <p className="page-subtitle">
            An operations tool for recruiting, screening, onboarding and staffing a network of
            external experts — shown here on a network of sample people who do not exist.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Link className="btn btn-primary" href="/apply/opportunities">
            See the applicant side
          </Link>
          <Link className="btn btn-secondary" href="/login">
            Operator sign-in
          </Link>
        </div>
      </header>

      <Alert tone="warning">
        <strong>Everything here is sample data.</strong> The {overview.network.totalExperts}{' '}
        experts, the projects and the seats were generated by a seeding script. Nobody was
        contacted: email is written to an in-app outbox and never sent. No payment has ever been
        made — the most a payment batch can be is exported to a CSV.
      </Alert>

      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <StatTile label="Experts in the network" value={overview.network.totalExperts} />
        <StatTile
          label="Seats filled"
          value={
            <>
              {seatsFilled}
              <span className="text-base font-normal text-ink-400">/{seatsRequested}</span>
            </>
          }
          sub="Each one an explicit confirmation"
        />
        <StatTile label="Open opportunities" value={overview.openOpportunities} />
        <StatTile
          label="Background jobs run"
          value={overview.jobsSucceeded}
          sub={
            overview.jobsFailed > 0 ? `${overview.jobsFailed} failed` : 'None failed permanently'
          }
        />
      </div>

      <div className="grid gap-5 lg:grid-cols-[minmax(0,3fr)_minmax(0,2fr)]">
        <Card
          title="How work moves through it"
          description="Sourcing, screening, staffing and delivery, with a person at every decision."
        >
          <ol className="space-y-4">
            {STEPS.map((step, index) => (
              <li key={step.title} className="grid grid-cols-[1.75rem_minmax(0,1fr)] gap-3">
                <span
                  className="grid h-7 w-7 place-items-center rounded-full bg-accent-50 text-xs font-bold text-accent-700"
                  aria-hidden="true"
                >
                  {index + 1}
                </span>
                <div>
                  <p className="text-sm font-semibold text-ink-900">{step.title}</p>
                  <p className="mt-0.5 text-sm text-ink-600">{step.body}</p>
                </div>
              </li>
            ))}
          </ol>
        </Card>

        <Card title="The network" description="Aggregate only. No individual record is shown.">
          <ul className="space-y-1.5">
            {overview.network.expertsByStatus.map((row) => (
              <li key={row.status} className="flex items-center justify-between gap-3">
                <StatusBadge status={row.status} />
                <span className="text-sm font-semibold tabular-nums text-ink-800">{row.count}</span>
              </li>
            ))}
          </ul>
        </Card>
      </div>

      <Card
        flush
        title="Projects"
        description="Seats are consumed by an explicit confirmation, one at a time."
      >
        <TableShell label="Sample projects">
          <thead>
            <tr>
              <th>Project</th>
              <th>Status</th>
              <th>Seats</th>
              <th>Required skill</th>
              <th className="text-right">Rate ceiling</th>
            </tr>
          </thead>
          <tbody>
            {overview.projects.map((project) => (
              <tr key={project.code}>
                <td>
                  <span className="cell-primary">{project.title}</span>
                  <span className="cell-meta font-mono">{project.code}</span>
                </td>
                <td>
                  <StatusBadge status={project.status} />
                </td>
                <td className="tabular-nums">
                  {project.seatsFilled}/{project.seatsRequested}
                </td>
                <td className="text-ink-600">{project.requirements.join(', ') || '—'}</td>
                <td className="text-right tabular-nums">
                  {project.maxHourlyRateCents
                    ? centsToRateDisplay(project.maxHourlyRateCents, 'USD')
                    : '—'}
                </td>
              </tr>
            ))}
          </tbody>
        </TableShell>
      </Card>

      {overview.ranking && (
        <Card
          title={`Matching, worked through on ${overview.ranking.projectCode}`}
          description={`${overview.ranking.algorithmVersion} · ${overview.ranking.consideredCount} considered · ${overview.ranking.rankedCount} ranked · ${overview.ranking.excludedCount} excluded`}
          actions={<Badge tone="muted">Deterministic rules</Badge>}
        >
          <p className="text-sm text-ink-700">
            No language model. The same inputs always produce the same ranking, and every exclusion
            says why — which is the part an operator has to be able to defend.
          </p>

          <div className="mt-4 grid gap-5 lg:grid-cols-2">
            <div>
              <h3 className="section-title">Top of the ranking</h3>
              <p className="field-hint">
                Identified by reference only. Names and contact details are not part of this view.
              </p>
              <ol className="mt-2 divide-y divide-ink-100 rounded-lg border border-ink-200">
                {overview.ranking.top.map((row) => (
                  <li
                    key={row.reference}
                    className="flex items-center justify-between gap-3 px-3 py-2 text-sm"
                  >
                    <span className="flex items-center gap-3">
                      <span className="w-5 text-xs tabular-nums text-ink-400">#{row.rank}</span>
                      <span className="font-mono text-xs">{row.reference}</span>
                    </span>
                    <span className="flex items-center gap-2">
                      <span
                        className="h-1.5 w-20 overflow-hidden rounded-full bg-ink-100"
                        aria-hidden="true"
                      >
                        <span
                          className="block h-full rounded-full bg-accent-500"
                          style={{ width: `${Math.max(2, Math.min(100, row.score))}%` }}
                        />
                      </span>
                      <span className="w-8 text-right text-xs font-semibold tabular-nums">
                        {row.score}
                      </span>
                    </span>
                  </li>
                ))}
              </ol>
            </div>

            <div>
              <h3 className="section-title">Why people were excluded</h3>
              <p className="field-hint">A hard filter, applied before any scoring.</p>
              <ul className="mt-2 divide-y divide-ink-100 rounded-lg border border-ink-200">
                {overview.ranking.exclusions.map((row) => (
                  <li
                    key={row.reason}
                    className="flex items-start justify-between gap-3 px-3 py-2 text-sm text-ink-700"
                  >
                    <span>{row.reason}</span>
                    <strong className="tabular-nums text-ink-900">{row.count}</strong>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </Card>
      )}

      <Card
        title="What this view deliberately does not show"
        description="The demo is a separate projection, not an account with the permissions turned down."
      >
        <ul className="grid gap-2 text-sm text-ink-700 sm:grid-cols-2">
          <li>Candidates, applications and screening answers — those are people’s words.</li>
          <li>
            The simulated outbox, which holds single-use sign-in links. A link read from it would be
            a working session.
          </li>
          <li>Payment items and batches, the activity history, and operator identities.</li>
          <li>Internal notes on any record, and any record not created by the seeding script.</li>
        </ul>
        <p className="mt-3 text-sm text-ink-600">
          Signing in as an operator shows all of it. That needs an account, and there is no shared
          demo password.
        </p>
      </Card>
    </div>
  );
}
