import { environmentLabel } from '@/lib/env';
import { centsToRateDisplay } from '@/lib/money';
import { formatDate, formatDateTime } from '@/lib/time';

/**
 * Message templates for the SIMULATED outbox.
 *
 * These render plain text only. Nothing in this file talks to an SMTP server,
 * an email API, or any external service - the rendered body is stored in the
 * OutboxMessage table and displayed in the operator UI.
 */
export interface RenderedMessage {
  subject: string;
  bodyText: string;
}

// Read per render rather than once at module load: the label depends on
// configuration, and a constant computed at import time would be frozen to
// whatever the first process to import this file happened to be.
function signature(): string {
  return [
    '',
    '--',
    `ExpertOps (${environmentLabel().toLowerCase()})`,
    'This message was generated by a simulated outbox and was not delivered to any mail server.',
  ].join('\n');
}

function block(lines: Array<string | false | null | undefined>): string {
  return lines.filter((line): line is string => typeof line === 'string').join('\n');
}

export interface InvitationEmailInput {
  expertName: string;
  projectTitle: string;
  projectCode: string;
  clientName: string;
  message: string;
  expiresAt: Date;
  portalUrl: string;
  startDate?: Date | null;
  endDate?: Date | null;
  maxHourlyRateCents?: number | null;
  currency?: string;
}

export function renderInvitationEmail(input: InvitationEmailInput): RenderedMessage {
  return {
    subject: `Project invitation: ${input.projectTitle} (${input.projectCode})`,
    bodyText: block([
      `Hello ${input.expertName},`,
      '',
      `You have been matched to a project for ${input.clientName}.`,
      '',
      `Project: ${input.projectTitle} (${input.projectCode})`,
      input.startDate ? `Starts: ${formatDate(input.startDate)}` : null,
      input.endDate ? `Ends: ${formatDate(input.endDate)}` : null,
      typeof input.maxHourlyRateCents === 'number'
        ? `Budgeted rate ceiling: ${centsToRateDisplay(input.maxHourlyRateCents, input.currency ?? 'USD')}`
        : null,
      '',
      input.message ? `Note from the ExpertOps team:\n${input.message}` : null,
      input.message ? '' : null,
      `Please respond by ${formatDateTime(input.expiresAt)}.`,
      '',
      'Open your portal to accept or decline:',
      input.portalUrl,
      signature(),
    ]),
  };
}

export interface ReminderEmailInput {
  expertName: string;
  projectTitle: string;
  projectCode: string;
  expiresAt: Date;
  portalUrl: string;
}

export function renderInvitationReminderEmail(input: ReminderEmailInput): RenderedMessage {
  return {
    subject: `Reminder: ${input.projectTitle} (${input.projectCode}) needs your response`,
    bodyText: block([
      `Hello ${input.expertName},`,
      '',
      `Your invitation to ${input.projectTitle} (${input.projectCode}) is still open.`,
      `It expires at ${formatDateTime(input.expiresAt)}.`,
      '',
      'Respond here:',
      input.portalUrl,
      signature(),
    ]),
  };
}

export interface ExpiryEmailInput {
  expertName: string;
  projectTitle: string;
  projectCode: string;
}

export function renderInvitationExpiredEmail(input: ExpiryEmailInput): RenderedMessage {
  return {
    subject: `Invitation closed: ${input.projectTitle} (${input.projectCode})`,
    bodyText: block([
      `Hello ${input.expertName},`,
      '',
      `The response window for ${input.projectTitle} (${input.projectCode}) has passed, so the`,
      'invitation has been closed automatically. No action is needed from you.',
      '',
      'We will be in touch about future projects.',
      signature(),
    ]),
  };
}

export interface OnboardingEmailInput {
  expertName: string;
  portalUrl: string;
  outstandingItems: string[];
}

export function renderOnboardingStartEmail(input: OnboardingEmailInput): RenderedMessage {
  return {
    subject: 'Next step: complete your ExpertOps onboarding',
    bodyText: block([
      `Hello ${input.expertName},`,
      '',
      'Thank you for accepting. Before you can be assigned to a project seat we need',
      'your onboarding checklist completed and verified by an operator.',
      '',
      'Outstanding items:',
      ...input.outstandingItems.map((item) => `  - ${item}`),
      '',
      'Complete them here:',
      input.portalUrl,
      signature(),
    ]),
  };
}

export function renderOnboardingNudgeEmail(input: OnboardingEmailInput): RenderedMessage {
  return {
    subject: 'Your ExpertOps onboarding is still open',
    bodyText: block([
      `Hello ${input.expertName},`,
      '',
      'Your onboarding checklist has items left to complete. Staffing cannot proceed',
      'until it is submitted and verified.',
      '',
      'Outstanding items:',
      ...input.outstandingItems.map((item) => `  - ${item}`),
      '',
      input.portalUrl,
      signature(),
    ]),
  };
}

export interface VerificationEmailInput {
  expertName: string;
  operatorName: string;
  note?: string | null;
}

export function renderOnboardingVerifiedEmail(input: VerificationEmailInput): RenderedMessage {
  return {
    subject: 'Your ExpertOps profile is verified',
    bodyText: block([
      `Hello ${input.expertName},`,
      '',
      `${input.operatorName} reviewed and verified your onboarding submission.`,
      'You are now eligible to be assigned to project seats.',
      input.note ? `\nOperator note: ${input.note}` : null,
      signature(),
    ]),
  };
}

export function renderOnboardingRejectedEmail(input: VerificationEmailInput): RenderedMessage {
  return {
    subject: 'Your ExpertOps onboarding needs changes',
    bodyText: block([
      `Hello ${input.expertName},`,
      '',
      `${input.operatorName} reviewed your onboarding submission and returned it for changes.`,
      input.note ? `\nReason: ${input.note}` : null,
      '',
      'You can update and resubmit your checklist from your portal.',
      signature(),
    ]),
  };
}

export interface AssignmentEmailInput {
  expertName: string;
  projectTitle: string;
  projectCode: string;
  clientName: string;
  hoursPerWeek: number;
  rateCents: number;
  currency: string;
  startDate?: Date | null;
  endDate?: Date | null;
}

export function renderAssignmentConfirmedEmail(input: AssignmentEmailInput): RenderedMessage {
  return {
    subject: `You are staffed on ${input.projectTitle} (${input.projectCode})`,
    bodyText: block([
      `Hello ${input.expertName},`,
      '',
      `You have been assigned a seat on ${input.projectTitle} for ${input.clientName}.`,
      '',
      `Allocation: ${input.hoursPerWeek} hours per week`,
      `Rate: ${centsToRateDisplay(input.rateCents, input.currency)}`,
      input.startDate ? `Start: ${formatDate(input.startDate)}` : null,
      input.endDate ? `End: ${formatDate(input.endDate)}` : null,
      '',
      'Your ExpertOps contact will follow up with scheduling details.',
      signature(),
    ]),
  };
}

export interface AssignmentReleaseEmailInput {
  expertName: string;
  projectTitle: string;
  projectCode: string;
  reason?: string | null;
}

export function renderAssignmentReleasedEmail(input: AssignmentReleaseEmailInput): RenderedMessage {
  return {
    subject: `Update on ${input.projectTitle} (${input.projectCode})`,
    bodyText: block([
      `Hello ${input.expertName},`,
      '',
      `Your seat on ${input.projectTitle} (${input.projectCode}) has been released.`,
      input.reason ? `\nReason given: ${input.reason}` : null,
      '',
      'This does not affect your standing in the network.',
      signature(),
    ]),
  };
}

export const TEMPLATE_NAMES = [
  'invitation.sent',
  'invitation.reminder',
  'invitation.expired',
  'onboarding.start',
  'onboarding.nudge',
  'onboarding.verified',
  'onboarding.rejected',
  'assignment.confirmed',
  'assignment.released',
] as const;

export type TemplateName = (typeof TEMPLATE_NAMES)[number];
